on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  generate-clients:
    strategy:
      matrix:
        api: ["merchant", "channel"]
        language: [php]
    runs-on: ubuntu-latest
    name: Generate ${{ matrix.language }} ${{ matrix.api }} Client
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.FRIENDS_OF_CE_SECRET }}

      - name: Get the version
        id: set-version
        run: |
          wget -O swagger.json "https://demo.channelengine.net/api/swagger/merchant/swagger.json"
          version=$(cat swagger.json | jq '.info.version')
          echo "The version is ${version}"
          echo "packageVersion=${version}" >> $GITHUB_OUTPUT

      # Use the action to generate a client package
      - name: Generate the client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: ${{ matrix.language }}
          openapi-url: "https://demo.channelengine.net/api/swagger/merchant/swagger.json"
          config-file: clients/${{ matrix.api }}-api-client-${{ matrix.language }}/config.json
          command-args: --artifact-version=${{ steps.set-version.outputs.packageVersion }} --output=clients/${{ matrix.api }}-api-client-${{ matrix.language }}

      - name: Publish
        run: |
          cd clients/${{ matrix.api }}-api-client-${{ matrix.language }}
          git config --global user.name 'Davide Pastore'
          git config --global user.email 'davidepastore@users.noreply.github.com'
          if [ -n "$(git status --porcelain)" ]; then
            echo "There are changes";
            git commit -a -m "Generate ${{ steps.set-version.outputs.packageVersion }} version"
            git tag -a "v${{ steps.set-version.outputs.packageVersion }}" -m "Version ${{ steps.set-version.outputs.packageVersion }}"
            git push origin main
            git push origin "v${{ steps.set-version.outputs.packageVersion }}"
          else
            echo "No changes";
          fi